const UserActionTypes = {
  LOGIN: 'user/LOGIN',
  LOGIN_SUCCESS: 'user/LOGIN_SUCCESS',
  LOGIN_ERROR: 'user/LOGIN_ERROR',
  LOGOUT: 'user/LOGOUT',
  REGISTER: 'user/REGISTER',
  REGISTER_SUCCESS: 'user/REGISTER_SUCCESS',
  REGISTER_ERROR: 'user/REGISTER_ERROR',
  UPDATE_PROFILE: 'user/UPDATE_PROFILE',
  UPDATE_PROFILE_SUCCESS: 'user/UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_ERROR: 'user/UPDATE_PROFILE_ERROR',
};

export default UserActionTypes;

